### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by Multiforge** [tapouillo/BMGlyphLabelSwift#1]
Hi, thanks for the great work converting this project to Swift. Once you have tested it fully, can you please add a podspec file and add it to Cocoapods library?

Looking forward using this with my Swift projects.

Many thanks

**Comment by tapouillo** [comment]
yes, will do ...  :)

**Comment by Multiforge** [comment]
Merci beaucoup :+1:

**Comment by tapouillo** [comment]
cocoapods is ready :)
you can use this in your Podfile targets:

pod 'BMGlyphLabelSwift', '0.1.0'
