### ISSUE TITLE
Memory Leaks from BMGlyphFont parser:didStartElement

### ISSUE THREAD

**Issue by jwrigh26** [tapouillo/BMGlyphLabelSwift#5]
Working with the files in a basic hello world project, I noticed right off that memory leaks are occurring. I've traced them down to inside the parser:didStartElement when the chars dictionary get's assigned values.

The memory leaks report wasn't showing exactly where it was occurring so I commented out code and re-commented until I sprung the leak again. Tried both Tapouillo's version and the fork from nacrossweb.
Both repos produce the same memory leak.

![screen shot 2016-05-13 at 5 51 55 pm](https://cloud.githubusercontent.com/assets/8534039/15262915/8284c9c8-1933-11e6-8ecf-90e6e0b62ede.png)
![screen shot 2016-05-13 at 5 52 13 pm](https://cloud.githubusercontent.com/assets/8534039/15262917/85226956-1933-11e6-974a-84af7aed16fb.png)

Here is another image from Instruments showing where the leaks are occurring
![screen shot 2016-05-13 at 6 01 12 pm](https://cloud.githubusercontent.com/assets/8534039/15263087/c9c6bb7e-1934-11e6-9228-68160ce3a640.png)
.

**Comment by tapouillo** [comment]
I tried to reproduce it, but with the current version of bmglyphlabelswift and the example, there is no leaks  showing in the instrument tool.
also if I look at your screenshot, the responsible library is saying libswiftCore. 
does it happen with this project or under a different environment ?

**Comment by jwrigh26** [comment]
Tried it under a hello world environment and a personal project.

**Comment by jwrigh26** [comment]
So I believe I found out what the issue is. String interpolation! In the font class when I replace the interpolated values with just strings, the memory issues go away. I'm starting to think there might be a bug in Xcode 7.3 that has collections leak memory when they append interpolated string values.

**Comment by tapouillo** [comment]
found something similar here: https://openradar.appspot.com/26366199
I will check that (need to upgrade to 7.3 first, didn't have time yet)

**Comment by tapouillo** [comment]
closing... project has been migrated to swift 3, please reopen an issue if you still have the problem :)
